log_level: DEBUG

n_jobs: 1

featurizer_type: HelloWorldFeaturizer
featurizer_parameters:

# classifier_type: HelloWorldBinaryLabelsClassifier
# classifier_parameters:
#   pos_label: apple

classifier_type: HelloWorldMultiLabelsClassifier
classifier_parameters:
  include: [apple, cherry]