log_level: DEBUG

n_jobs: 1

featurizer_type: HelloWorldFeaturizer
featurizer_parameters:

classifier_type: HelloWorldBinaryLabelsClassifier
classifier_parameters:

# classifier_type: HelloWorldMultiLabelsClassifier
# classifier_parameters:
