log_level: DEBUG

n_jobs: 1

featurizer_type: helloworld.featurizers.HelloWorldFeaturizer
featurizer_parameters:
  feature_dims: 10

classifier_type: helloworld.classifiers.HelloWorldBinaryLabelsClassifier
# classifier_type: helloworld.classifiers.HelloWorldMultiLabelsClassifier
# classifier_type: helloworld.classifiers.HelloWorldMulticlassClassifier
classifier_parameters:
  pos_label: apple
